name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        
        steps:
          - uses: actions/checkout@master
          - uses: seanmiddleditch/gha-setup-ninja@master
          - name: Configure CMake with Ninja
            run: |
              mkdir build
              cd build
              cmake -G Ninja ..
          - name: Compile
            run: cmake --build build
    
